# ! Selecting MVL dataset
workspace_dir: ${rel_path:../}

ckpt: zind
cuda_device: 0

output_dir: ${dirs.mlc_label_dir}/${id_exp}
id_exp: hn_${ckpt}__mp3d_fpe__mlc

# mp3d_fpe_dir: /media/public_dataset/MP3D_360_FPE/360_layout_challenge/
dirs: 
  mp3d_fpe_dir: ${workspace_dir}/assets/mp3d_fpe_dataset
  mlc_label_dir: ${workspace_dir}/assets/mlc_labels
  output_dir: ${workspace_dir}/assets/mlc_results

auto_loading:
    trained_models: ${rel_path:./trained_models.yaml}
    data_dir: ${rel_path:./datasets.yaml}
    dirs: ${rel_path:./global_directories.yaml}
    scale_recover: ${rel_path:./scale_recover.yaml}
    mvl_data: ${rel_path:./mvl_data.yaml}

runners:
  mvl:
    label: mlc_label
    data_dir: ${mvl_data.mp3d_fpe}
    scene_list: ${mvl_data.mp3d_fpe.scene_list_train}
    apply_scale_recover: True
    batch_size: 15
    size: -1
    grid_ref: 0.1
    min_likelihood_percent: 0.000001
    padding: 20
    max_room_factor_size: 2
    std_kernel: [30, 10, 5]


model:
  ly_model: HorizonNet
  ckpt: ${trained_models.${ckpt}.ckpt}
  optimizer: Adam
  loss: weighted_L1
  min_std: 0.001
  epochs: 25
  save_every: 1 
  lr: 0.00005
  lr_decay_rate: 0.90
  seed: 594277
  bn_momentum: 0
  freeze_earlier_blocks: -1
  beta1: 0.9
  weight_decay: 0.0