
# ! Selecting MVL dataset
workspace: ${rel_path:../}

ckpt: mp3d
cuda_device: 1
target_dataset: mp3d_fpe

output_dir: ${dirs.mlc_label_dir}/${id_exp}

id_exp: hn_${ckpt}__${target_dataset}__mlc

auto_loading:
    trained_models: ${rel_path:./trained_models.yaml}
    data_dir: ${rel_path:./datasets.yaml}
    dirs: ${rel_path:./global_directories.yaml}
    scale_recover: ${rel_path:./scale_recover.yaml}
    mp3d_fpe: ${rel_path:./mvl_data_cfg.yaml}

runners:
  mvl:
    label: mlc_label
    data_dir: ${data_dir.${target_dataset}}
    scene_list: ${data_mvl.scene_list_train}
    apply_scale_recover: True
    batch_size: 15
    size: -1
    grid_ref: 0.1
    min_likelihood_percent: 0.000001
    padding: 20
    max_room_factor_size: 2


model:
  ly_model: HorizonNet
  ckpt: ${trained_models.${ckpt}.ckpt}
  optimizer: Adam
  loss: weighted_L1
  min_std: 0.001
  epochs: 25
  save_every: 1 
  lr: 0.00005
  lr_decay_rate: 0.90
  seed: 594277
  bn_momentum: 0
  freeze_earlier_blocks: -1
  beta1: 0.9
  weight_decay: 0.0