mp3d_fpe:
  name: mp3d_fpe
  scene_list_train: ${rel_path:../data/${target_dataset}/mp3d_fpe_room_scenes_train.json}
  scene_list_test: ${rel_path:../data/${target_dataset}/mp3d_fpe_room_scenes_test.json}
  valid_iou_data: ${data_dir.mp3d_fpe_test}
  img_dir: /media/public_dataset/MP3D_360_FPE/360_layout_challenge/img
  geometry_info: /media/public_dataset/MP3D_360_FPE/360_layout_challenge/geometry_info
